nelmio_api_doc:
    documentation:
        info:
            title: Synfony4 base API project
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc|doc.json)$)
